{% set name = "dphtools" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dphtools-{{ version }}.tar.gz
  sha256: 7dbc11597977b40db716e9e7f5214449e7ba6cd0e53825bb5f7d6c86d7149a69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.8
    - scikit-image
    - scipy

test:
  imports:
    - dphtools
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/david-hoffman/dphtools
  summary: Tools for optics and image analysis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - david-hoffman
    - goanpeca
